name = input("what is ur name?")
email_id = input("what is ur email id?")
ph_no = input("enter ur phone number:")
print("***************************************")
print("user name"+ name)
print ("email id"+email_id)
print("ph:"+ph_no)